<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title><?= ucfirst($report_type) ?> Inventory Report - A We Green Enterprise</title>
  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/css/bootstrap.min.css" rel="stylesheet">
  <style>
    @media print {
      .no-print {
        display: none !important;
      }

      body {
        print-color-adjust: exact;
        -webkit-print-color-adjust: exact;
      }

      @page {
        size: A4;
        margin: 15mm;
      }
    }

    body {
      font-size: 11px;
    }

    .report-header {
      border-bottom: 3px solid #16A249;
      padding-bottom: 15px;
      margin-bottom: 20px;
    }

    .company-logo {
      max-height: 70px;
      width: auto;
    }

    .report-title {
      color: #16A249;
      font-weight: bold;
      font-size: 24px;
    }

    .info-label {
      font-weight: 600;
      color: #666;
    }

    .table-header {
      background-color: #16A249 !important;
      color: white !important;
    }

    .status-badge {
      padding: 3px 10px;
      border-radius: 10px;
      font-size: 10px;
      font-weight: 500;
      display: inline-block;
    }

    .status-instock {
      background-color: #d4edda;
      color: #155724;
    }

    .status-lowstock {
      background-color: #fff3cd;
      color: #856404;
    }

    .status-outstock {
      background-color: #f8d7da;
      color: #721c24;
    }

    .status-delivered {
      background-color: #d1ecf1;
      color: #0c5460;
    }

    .summary-card {
      border-left: 4px solid #16A249;
      background-color: #f8f9fa;
      padding: 12px;
      margin-bottom: 15px;
    }

    .activity-log {
      background-color: #f8f9fa;
      border-radius: 4px;
      padding: 8px;
      margin-bottom: 8px;
      font-size: 10px;
    }

    .activity-create {
      border-left: 3px solid #28a745;
    }

    .activity-update {
      border-left: 3px solid #007bff;
    }

    .activity-archive {
      border-left: 3px solid #dc3545;
    }

    footer {
      margin-top: 30px;
      padding-top: 15px;
      border-top: 2px solid #e0e0e0;
      font-size: 10px;
      color: #666;
    }

    table {
      font-size: 10px;
    }

    .btn-generate-pdf {
      background-color: #dc3545;
      border: none;
      padding: 12px 30px;
      font-size: 16px;
    }

    .btn-generate-pdf:hover {
      background-color: #bb2d3b;
    }
  </style>
</head>

<body>
  <div class="container my-4">

    <!-- ACTION BUTTONS -->
    <div class="text-end mb-3 no-print">
      <button onclick="generatePDF()" class="btn btn-danger btn-generate-pdf me-2">
        <i class="fa-solid fa-file-pdf"></i> Generate PDF
      </button>
      <button onclick="window.print()" class="btn btn-success btn-lg">
        <i class="fa-solid fa-print"></i> Print Report
      </button>
      <button onclick="window.close()" class="btn btn-secondary btn-lg">
        Close
      </button>
    </div>

    <div id="report-content">
      <!-- REPORT HEADER -->
      <div class="report-header">
        <div class="row align-items-center">
          <div class="col-md-2 text-center">
            <img src="../../INCLUDES/LP-IMAGES/awegreen-logo.png" alt="A We Green Enterprise Logo" class="company-logo">
          </div>
          <div class="col-md-10">
            <h1 class="report-title mb-2">A WE GREEN ENTERPRISE</h1>
            <p class="mb-1"><strong>Main Office:</strong> ATH Phase 4 Blk 51 Lot 30 Brgy. A. Olaes, GMA, Cavite 4117</p>
            <p class="mb-1">
              <strong>Contact:</strong>
              Globe: 0917 752 3343 | Smart: 0998 884 5671
            </p>
            <p class="mb-0"><strong>Email:</strong> awegreenenterprise@gmail.com</p>
          </div>
        </div>
      </div>

      <!-- REPORT INFO -->
      <div class="row mb-3">
        <div class="col-md-12">
          <h2 class="h4 text-uppercase"><?= ucfirst($report_type) ?> Inventory Report</h2>
          <p class="mb-1"><span class="info-label">Report Period:</span> <?= date('F d, Y', strtotime($date_from)) ?> - <?= date('F d, Y', strtotime($date_to)) ?></p>
          <p class="mb-1"><span class="info-label">Generated On:</span> <?= date('F d, Y h:i A') ?></p>
          <p class="mb-1"><span class="info-label">Generated By:</span> <?= htmlspecialchars($employee_full_name) ?></p>
        </div>
      </div>

      <!-- SUMMARY STATISTICS -->
      <div class="summary-card">
        <h3 class="h6 mb-2">Summary Statistics</h3>
        <div class="row">
          <div class="col-md-3">
            <p class="mb-1 text-muted small">Total Items</p>
            <h4 class="h5 text-primary mb-0"><?= count($report_items) ?></h4>
          </div>
          <div class="col-md-3">
            <p class="mb-1 text-muted small">In Stock</p>
            <h4 class="h5 text-success mb-0">
              <?= count(array_filter($report_items, fn($item) => $item['status'] === 'In Stock')) ?>
            </h4>
          </div>
          <div class="col-md-3">
            <p class="mb-1 text-muted small">Low Stock</p>
            <h4 class="h5 text-warning mb-0">
              <?= count(array_filter($report_items, fn($item) => $item['status'] === 'Low Stock')) ?>
            </h4>
          </div>
          <div class="col-md-3">
            <p class="mb-1 text-muted small">Out of Stock</p>
            <h4 class="h5 text-danger mb-0">
              <?= count(array_filter($report_items, fn($item) => $item['status'] === 'Out of Stock')) ?>
            </h4>
          </div>
        </div>
      </div>

      <!-- INVENTORY ITEMS TABLE -->
      <div class="mb-4">
        <h3 class="h6 mb-2">Inventory Items Details</h3>
        <div class="table-responsive">
          <table class="table table-bordered table-sm">
            <thead class="table-header">
              <tr>
                <th style="width: 3%;">#</th>
                <th style="width: 18%;">Item Name</th>
                <th style="width: 12%;">Category</th>
                <th style="width: 8%;">Quantity</th>
                <th style="width: 8%;">Price (₱)</th>
                <th style="width: 8%;">Selling (₱)</th>
                <th style="width: 10%;">Status</th>
                <th style="width: 12%;">Location</th>
                <th style="width: 12%;">Supplier</th>
                <th style="width: 9%;">Warranty</th>
              </tr>
            </thead>
            <tbody>
              <?php
              $total_value = 0;
              foreach ($report_items as $index => $item):
                $item_value = $item['quantity'] * $item['price'];
                $total_value += $item_value;

                // Format warranty
                $warranty = '';
                if ($item['warranty_years'] > 0) $warranty .= $item['warranty_years'] . 'y ';
                if ($item['warranty_months'] > 0) $warranty .= $item['warranty_months'] . 'm ';
                if ($item['warranty_days'] > 0) $warranty .= $item['warranty_days'] . 'd';
                $warranty = trim($warranty) ?: 'N/A';
              ?>
                <tr>
                  <td><?= $index + 1 ?></td>
                  <td><?= htmlspecialchars($item['item_name']) ?></td>
                  <td><?= htmlspecialchars($item['category']) ?></td>
                  <td><?= $item['quantity'] ?> <?= htmlspecialchars($item['quantity_unit']) ?></td>
                  <td>₱<?= number_format($item['price'], 2) ?></td>
                  <td>₱<?= number_format($item['selling_price'], 2) ?></td>
                  <td>
                    <?php
                    $status = $item['status'];
                    $class = match ($status) {
                      "In Stock"       => "status-badge status-instock",
                      "Low Stock"      => "status-badge status-lowstock",
                      "Out of Stock"   => "status-badge status-outstock",
                      "To Be Delivered" => "status-badge status-delivered",
                      default          => "status-badge"
                    };
                    ?>
                    <span class="<?= $class ?>"><?= htmlspecialchars($status) ?></span>
                  </td>
                  <td><?= htmlspecialchars($item['location']) ?></td>
                  <td><?= htmlspecialchars($item['supplier']) ?></td>
                  <td><?= $warranty ?></td>
                </tr>
              <?php endforeach; ?>
            </tbody>
            <tfoot>
              <tr class="table-light fw-bold">
                <td colspan="3" class="text-end">Total Inventory Value:</td>
                <td colspan="7">₱<?= number_format($total_value, 2) ?></td>
              </tr>
            </tfoot>
          </table>
        </div>
      </div>

      <!-- FOOTER -->
      <footer class="text-center">
        <p class="mb-1">This is a system-generated report from A We Green Enterprise Inventory Management System</p>
        <p class="mb-0">For inquiries, please contact us at awegreenenterprise@gmail.com</p>
        <p class="mt-2 mb-0">
          <strong>A We Green Enterprise</strong> |
          Main Office: ATH Phase 4 Blk 51 Lot 30 Brgy. A. Olaes, GMA, Cavite 4117
        </p>
      </footer>
    </div>

  </div>

  <!-- Font Awesome -->
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.4.0/css/all.min.css">

  <!-- jsPDF and html2canvas for PDF generation -->
  <script src="https://cdnjs.cloudflare.com/ajax/libs/html2canvas/1.4.1/html2canvas.min.js"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/jspdf/2.5.1/jspdf.umd.min.js"></script>

  <script>
    async function generatePDF() {
      const {
        jsPDF
      } = window.jspdf;
      const content = document.getElementById('report-content');

      // Show loading message
      const originalButton = event.target;
      const originalText = originalButton.innerHTML;
      originalButton.innerHTML = '<i class="fa-solid fa-spinner fa-spin"></i> Generating PDF...';
      originalButton.disabled = true;

      try {
        // Convert HTML to canvas
        const canvas = await html2canvas(content, {
          scale: 2,
          useCORS: true,
          logging: false,
          backgroundColor: '#ffffff'
        });

        const imgData = canvas.toDataURL('image/png');

        // Create PDF
        const pdf = new jsPDF({
          orientation: 'portrait',
          unit: 'mm',
          format: 'a4'
        });

        const imgWidth = 210; // A4 width in mm
        const pageHeight = 297; // A4 height in mm
        const imgHeight = (canvas.height * imgWidth) / canvas.width;
        let heightLeft = imgHeight;
        let position = 0;

        // Add first page
        pdf.addImage(imgData, 'PNG', 0, position, imgWidth, imgHeight);
        heightLeft -= pageHeight;

        // Add additional pages if needed
        while (heightLeft > 0) {
          position = heightLeft - imgHeight;
          pdf.addPage();
          pdf.addImage(imgData, 'PNG', 0, position, imgWidth, imgHeight);
          heightLeft -= pageHeight;
        }

        // Save PDF
        const filename = '<?= ucfirst($report_type) ?>_Inventory_Report_<?= date("Y-m-d") ?>.pdf';
        pdf.save(filename);

        // Reset button
        originalButton.innerHTML = originalText;
        originalButton.disabled = false;

      } catch (error) {
        console.error('Error generating PDF:', error);
        alert('Error generating PDF. Please try using the Print button instead.');
        originalButton.innerHTML = originalText;
        originalButton.disabled = false;
      }
    }

  
  </script>
</body>

</html>